#if !defined(AGRICOS_ERROR_CODES_H)
#define AGRICOS_ERROR_CODES_H

#define AGRICOS_ERROR_TIME_PROVIDER_NOT_DEFINED 0x01
#define AGRICOS_ERROR_OUT_FUNCTION_NOT_DEFINED 0x02

#endif // AGRICOS_ERROR_CODES_H
