#if !defined(AGRICOS_KERNEL_TYPES_RTC_MODE_H)
#define AGRICOS_KERNEL_TYPES_RTC_MODE_H

typedef enum {
    RTC_30_MINUTES,
    RTC_15_MINUTES,
    RTC_2_MINUTES,
    RTC_OFF,
} RTCMode_e;

#endif // AGRICOS_KERNEL_TYPES_RTC_MODE_H
