#if !defined(__TYPES_SENSOR_PROTOCOLS_H)
#define __TYPES_SENSOR_PROTOCOLS_H

typedef enum
{
    SENSOR_PROTOCOL_I2C,
    SENSOR_PROTOCOL_DDI,
    SENSOR_PROTOCOL_SPI,
    SENSOR_PROTOCOL_MODBUS,
    SENSOR_PROTOCOL_SERIAL,
    SENSOR_PROTOCOL_ANALOG
} SensorProtocols_e;

#endif  // __TYPES_SENSOR_PROTOCOLS_H
